version: 2

jobs:
  build:
    docker:
      - image: circleci/php:5.6-node-browsers
    steps:
      - checkout
      - run:
          name: Install composer
          command: curl -sS https://getcomposer.org/installer | php -- --filename=composer
      - ./composer install
      - ./application/test/phpunit
