version: 2

jobs:
  build:
    docker:
      - image: circleci/php:5.6-node-browsers
      - image: tkuchiki/delayed-mysql
        ports:
          - "3306:3306"
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: circleci
    steps:
      - checkout
      - run:
          name: Install composer
          command: curl -sS https://getcomposer.org/installer | php -- --filename=composer
      - run:
          name: Wait for DB
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run: composer install
      - run: sudo docker-php-ext-install zip pdo pdo_mysql
      - run:
          name: Mysql database
          command: mysql  -h 127.0.0.1 -u root < db/sweregrade.sql
      - run:  cd application/tests/ && ../../vendor/bin/phpunit