version: 2

jobs:
  build:
    docker:
      - image: circleci/php:5.6-node-browsers
      - image: circleci/mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    steps:
      - checkout
      - run:
          name: Install composer
          command: curl -sS https://getcomposer.org/installer | php -- --filename=composer
      - run: composer install
      - run: sudo docker-php-ext-install zip pdo pdo_mysql
      - run:
          name: Mysql database
          command: mysql  -h 127.0.0.1 -u root < db/sweregrade.sql
      - run:  cd application/tests/ && ../../vendor/bin/phpunit