version: 2

jobs:
  build:
    docker:
      - image: circleci/php:5.6-node-browsers
    steps:
      - checkout
      - run:
          name: Install composer
          command: curl -sS https://getcomposer.org/installer | php -- --filename=composer
      - run: composer install
      - run:
          name: Instalk phpunit
          command: bash -c "wget https://phar.phpunit.de/phpunit-6.5.phar \
        chmod +x phpunit-6.5.phar \
        sudo mv phpunit-6.5.phar /usr/local/bin/phpunit \
        phpunit --version"
      - run: cd application/tests/
      - run: phpunit
